backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    label_singular: 'Article'
    folder: 'content/articles'
    identifier_field: 'title'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Date', widget: 'datetime' }
      - {
          name: 'teaser',
          label: 'Teaser',
          widget: 'string',
          hint: 'Short Description (20 to 140 chars)',
          pattern: ['^.{20,140}$', 'Must be between 20 and 140 characters'],
        }
      - {
          name: 'thumbnail',
          label: 'Thumbnail',
          widget: 'image',
          hint: 'Size 800x800 px',
        }
      - { name: 'tags', label: 'Tags', widget: 'list', add_to_top: true }
      - { name: 'body', label: 'Body', widget: 'markdown' }
