backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    label_singular: 'Article'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Publish Date', widget: 'datetime' }
      - { name: 'teaser', label: 'Teaser', widget: 'string', hint: 'Short Description (20 to 140 chars)', pattern: ['^.{20,140}$', "Must be between 20 and 140 characters"] }
      - { name: 'thumbnail', label: "Featured Image", widget: 'image', hint: 'Size 800x800 px' }
      - { name: 'body', label: 'Body', widget: 'markdown' }