backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
logo_url: static/img/p2vLogo-300.svg

collections:
  - name: 'blog'
    label: 'Blog'
    label_singular: 'Article'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    editor:
    preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: 'MMM YYYY' }
      - { label: 'Teaser', name: 'teaser', widget: 'string' }
      - { label: "Featured Image", name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }